defmodule Mailers.MedsPaymentReceipt do
  alias Mailers.Helpers
  @utc_timezone "Asia/Dubai"
  def generate_receipt(attrs) do
    medication_items =
      attrs.medication_items
      |> generate_table_items()
      |> medicine_section()

    receipt_body(
      payment_section(attrs),
      patient_section(attrs),
      specialist_section(attrs),
      medication_items
    )
  end

  def receipt_body(payment, patient, specialist, medicine) do
    """
    <!DOCTYPE html>
    <html lang="en">
      #{head_section()}
    <body>
    <header>
        <p class="address">Building 72,<br>
            Dubai Healthcase City, Dubai<br>
            Contact: +971 4 453 2722<br>
            www.dronline.ai<br>
            info@dronline.me</p>
        <p class="center-title">PRESCRIPTION RECEIPT</p>
        <img src="priv/static/assets/dr-logo.png" alt="DrOnline-Logo">
    </header>
    <div class="pdf-content">
        <!-- Payment -->
        #{payment}
        <!-- Patient section -->
        #{patient}
        <!-- Specialist section -->
        #{specialist}
        <!-- Medicine table -->
        #{medicine}

    </div>
    </body>
    </html>
    """
  end

  @doc """
  Accepts medication items
  `[%{sr_no: 1, name: "name", quantity: 1, frequency: "diraction", duration: "refill"}]`
  """
  def generate_table_items(content) do
    content
    |> Enum.map(fn item ->
      [
        :tr,
        [:td, "#{item.sr_no}"],
        [:td, "#{item.name}"],
        [:td, "#{item.quantity}"],
        [:td, "#{item.frequency}"],
        [:td, "#{item.duration}"]
      ]
    end)
    |> Sneeze.render()
  end

  @doc """
  Accepts HTML string generated by `generat_table_items(content)`
  """
  def medicine_section(items) do
    """
    <h4 class="table-title">Assigned Medications</h4>
    <table class="table">
     <tr>
         <th>Sr No</th>
         <th>Name of the Drugs & Strength</th>
         <th>Quantity</th>
         <th>Frequency</th>
         <th>Duration</th>
     </tr>
    #{items}
    </table>

    """
  end

  @doc """
  Accepts `%{amount: 23, currency: "AED", date: "date"}`
  """
  def payment_section(attrs) do
    """
    <div class="container">
      #{title_section("Payment")}
       <table>
          <tr>
            <td>Amount:  #{attrs.amount}</td>
            <td> </td>
            <td> #{attrs.currency}, </td>
            <td> </td>
            <td></td>
            <td>    Date: #{Helpers.humanize_datetime(attrs.date, @utc_timezone)}</td>
          </tr>
      </table>
    </div>
    """
  end

  @doc """
  Accepts `Strint()` `title`
  """
  def title_section(title) do
    """
    <span class="table-header-title">#{title}</span>
    """
  end

  @doc """
  Accepts `%{patient_name: "name", order_id: "uuid"}`
  """
  def patient_section(attrs) do
    """
    <div class="container">
            #{title_section("Patient")}
            <table>
                <tr>
                    <td>Name:  #{attrs.patient_name},</td>
                    <td></td>
                    <td>    Order-No:  #{attrs.order_id}</td>
                </tr>
            </table>
        </div>
    """
  end

  @doc """
  Accepts `%{specialist_name: "name"}`
  """

  def specialist_section(attrs) do
    """
    <div class="container">
            #{title_section("Specialist")}
            <table>
                <tr>
                  <td>Name:  #{attrs.specialist_name}</td>
                </tr>
            </table>
        </div>
    """
  end

  def head_section do
    """
    <head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <style>
        header {
            display: flex;
            align-items: center;
            padding: 10px;
            align-content: center;
        }
        header img {
            height: 30px;
            margin-right: 20px;
            margin-left: auto;
        }
        .center-title {
            background-color: #000;
            color: #F0F0F0;
            padding: 10px;
            align-items: center;
            margin-left: auto;
            border-radius: 2%;
        }
        .address {
            font-size: smaller;
        }
        .table-header-title {
            font-weight: bold;
        }
        .container {
            display: grid;
            gap: 20px;
            padding: 20px;
            align-content: center;
        }
        .table-title {
            display: flex;
            justify-content: center;
        }
        .table {
            display: flex;
            justify-content: center;
            font-family: Arial, Helvetica, sans-serif;
            border-collapse: collapse;
        }
        .table td,
        .table th {
            border: 1px solid #000;
            padding: 10px;
        }
    </style>
    </head>
    """
  end
end
